### ISSUE TITLE
fsatrace cannot run cabal: setModificationTime: invalid argument

### ISSUE THREAD

**Issue by peti** [jacereda/fsatrace#16]
I'm seeing the following error in Linux/x86_64 using the latest git version of fsatrace:

~~~~
$ fsatrace rwm /tmp/foo -- cabal unpack -v0 base-orphans-0.5.4
base-orphans-0.5.4/: setModificationTime: invalid argument (Bad file
descriptor)
fsatrace?�~�(1072): error: command failed with code 1
argv[0]=cabal
argv[1]=unpack
argv[2]=-v0
argv[3]=base-orphans-0.5.4
~~~~

Is that a known problem? Am I doing something wrong?

**Comment by jacereda** [comment]
Looks like the problem is https://github.com/jacereda/fsatrace/blob/master/src/unix/fsatraceso.c#L451

It should instead call utimes() with an appropriate conversion from `timespec` to `timeval`. Unfortunately I won't be able to work on it until next week.

**Comment by jacereda** [comment]
I attempted the fix on a "Bash on Ubuntu" installation that unfortunately can't run any Haskell executables due to https://github.com/Microsoft/BashOnWindows/issues/307

Could you check if it works now?

**Comment by peti** [comment]
The new version produces a different error message here:

~~~~
$ fsatrace rwm /tmp/foo -- cabal unpack -v0 base-orphans-0.5.4
base-orphans-0.5.4/: setModificationTime: invalid argument (Invalid argument)
fsatrace(8493): error: command failed with code 1
argv[0]=cabal
argv[1]=unpack
argv[2]=-v0
argv[3]=base-orphans-0.5.4
~~~~

**Comment by jacereda** [comment]
Should be fine now.
