### ISSUE TITLE
Changes for GHC 8.0.2

### ISSUE THREAD

**Issue by ndmitchell** [jacereda/fsatrace#17]
I changed the script to work with GHC 8.0.2. A few minor issues which I'll pull request later, but the real issue was that two files define InterlockedAdd, namely:

* C:\Users\Neil\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\mingw\x86_64-w64-mingw32\include\psdk_inc\intrin-impl.h
* C:\Users\Neil\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\mingw\x86_64-w64-mingw32\include\ddk\wdm.h

I worked around that by adding:

```
#define __INTRINSIC_DEFINED__InterlockedAdd
#define __INTRINSIC_DEFINED__InterlockedAdd64
```

In hooks, which is vile. But is it acceptable? Or any other ideas how to avoid it?

**Comment by jacereda** [comment]
Hi Neil, sorry for the delay.

I don't have a Windows box at hand, I'll try to borrow one next week.

**Comment by jacereda** [comment]
Can you check the ghc-8.0.2 branch? I've updated the README with installation instructions.

**Comment by ndmitchell** [comment]
I tried the `ghc-8.0.2` branch and it worked really well. Only minor niggle was that on my system `stack exec` didn't work until I typed `stack setup`. Fortunately, I believe that's getting fixed in https://github.com/commercialhaskell/stack/pull/3231.

**Comment by jacereda** [comment]
Is this the sequence you used?

    stack setup 8.0.2 --arch=i386
    stack setup 8.0.2 --arch=x86_64
    stack exec -- pacman -S make
    stack exec -- make

**Comment by ndmitchell** [comment]
Yep. When I got to the first `stack exec` it said I couldn't run `stack exec` since my global resolver specified 7.10 and I hadn't got a 7.10, but I should `stack setup`. In truth, I just ran `stack config set resolver nightly` which updated my global resolver to one using 8.0.2, which I do have, and it ran fine.

**Comment by jacereda** [comment]
I guess this can be closed now. Did you receive my thanks email regarding shake?

**Comment by ndmitchell** [comment]
I did, I just hadn't got round to replying yet - life being hectic!
