### ISSUE TITLE
fsatrace isn't recording executable being run as a "read".

### ISSUE THREAD

**Issue by spall** [jacereda/fsatrace#26]
On Linux, fsatrace doesn't appear to record the executable it is running as a  "read".  
Tagging @ndmitchell; since we are using fsatrace in Rattle.

**Comment by jacereda** [comment]
Most of the time, `exec` is preceded by a `stat`, do you get that one at least? (It's reported as `q`).
For the purposes of a build system, I'd handle a query the same ways as a read.

**Comment by spall** [comment]
No, I don't see anything; the function parsing the fsatrace output gives me an empty list.  Let me know if you need more information and I will do my best.

**Comment by jacereda** [comment]
What's the command?

**Comment by spall** [comment]
https://github.com/ndmitchell/rattle/blob/86fe329ff117c6a9d70e835d99bb6925a4e3a95e/test/Test.hs#L32

**Comment by jacereda** [comment]
Can you check if https://github.com/jacereda/fsatrace/commit/b11acd9c5b7bf93b9a990fd337e190daf889b083 fixes it for you?

**Comment by spall** [comment]
Thank you, "Main" now registers as an "r".
