### ISSUE TITLE
Clarify (or clean up) the Windows makefile

### ISSUE THREAD

**Issue by ndmitchell** [jacereda/fsatrace#27]
While taking a look around I saw in `win.mk`:

```
SRCS32=src/win/fsatracedll.c src/win/inject.c src/win/patch.c src/win/hooks.c src/emit.c src/win/shm.c src/win/handle.c src/win/utf8.c src/win/dbg.c src/win/inject.c
SRCS64=$(SRCS32) src/win/inject.c
```

So SRCS64 = SRCS32 + inject.c. But inject.c is already is SRCS32? Unlikely to be harmful, but I guess it's a mistake?

**Comment by jacereda** [comment]
Worse than that, it's also replicated in SRCS32 :)

I left SRCS32=SRCS64. 

Thanks!
