### ISSUE TITLE
Have make run stack setup for you

### ISSUE THREAD

**Issue by ndmitchell** [jacereda/fsatrace#6]
Not sure if this is a good idea, but `make` on Windows could run `stack setup` if it couldn't find the necessary compilers but can find stack. Would allow simplifying the instructions.

**Comment by ndmitchell** [comment]
To be honest, now I've done it on all the computers I care about, it really wasn't too difficult - maybe that's too close integration with stack for comfort.

**Comment by jacereda** [comment]
Since some people might prefer to use their installed compilers I guess this should be closed.
