### ISSUE TITLE
Add --verbose flag

### ISSUE THREAD

**Issue by ndmitchell** [jacereda/fsatrace#7]
It would be really useful to have a --verbose flag to say exactly what the argv arguments to spawn, or the single command line to CreateProcess, is. At the moment I'm having to guess it.

**Comment by jacereda** [comment]
https://github.com/jacereda/fsatrace/compare/file-args implements it:

    fsatrace v<more flags> - -- cp /bin/ls /tmp/

**Comment by ndmitchell** [comment]
Have you thought about a more traditional syntax? I could imagine anything with a leading `-` (e.g. `-v` and `--verbose`) being treated as a flag, the first non-flag argument being the output file, and the remaining non-flag arguments being the command line. Coupled with the traditional `--` syntax to say all subsequent flags are arguments even if they begin with `-`, you can still write:

    fsatrace --verbose - -- cp /bin/ls /tmp/

But in fact the `--` becomes optional (in this example) and you are following the same rules as lots of other programs.

**Comment by jacereda** [comment]
Yes, at some point. Maybe even use getopt now that VS is no longer in the equation. I'm not in a hurry with this though, getting the right behaviour should now be the priority.
